#cloud-config
package_update: true
package_upgrade: true
packages:
  - apt-transport-https
  - ca-certificates
  - curl
  - gnupg
  - lsb-release
  - openssh-client

users:
  - name: cluster
    ssh-authorized-keys:
      - "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIJxMut6GKRjgrfgZ5xQJyjy5QtliIshWWXSuGicZ4M6y ajaorqb@gmail.com"
    sudo: ALL=(ALL) NOPASSWD:ALL
    shell: /bin/bash

write_files:
  - path: /etc/modules-load.d/k8s.conf
    content: |
      overlay
      br_netfilter

  # Write the SSH private key for master access
  - path: /home/cluster/.ssh/master_access
    owner: cluster:cluster
    permissions: '0600'
    content: |
      -----BEGIN OPENSSH PRIVATE KEY-----
      b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAAAMwAAAAtzc2gtZW
      QyNTUxOQAAACCcTLrehikY4K34GecUCco8uULZYiLIVll0rhonGeDOsgAAAJilpCiopaQo
      qAAAAAtzc2gtZWQyNTUxOQAAACCcTLrehikY4K34GecUCco8uULZYiLIVll0rhonGeDOsg
      AAAEArFpYXm8bPXxI556sbBYXOnEE6Du8+KzSjgVF1T8VEDJxMut6GKRjgrfgZ5xQJyjy5
      QtliIshWWXSuGicZ4M6yAAAAEWFqYW9ycWJAZ21haWwuY29tAQIDBA==
      -----END OPENSSH PRIVATE KEY-----


runcmd:
  # Load kernel modules
  - modprobe overlay
  - modprobe br_netfilter

  # Configure sysctl parameters
  - echo "net.bridge.bridge-nf-call-iptables = 1" >> /etc/sysctl.d/k8s.conf
  - echo "net.bridge.bridge-nf-call-ip6tables = 1" >> /etc/sysctl.d/k8s.conf
  - echo "net.ipv4.ip_forward = 1" >> /etc/sysctl.d/k8s.conf
  - sysctl --system

  # create keyrings folder
  - mkdir -p -m 755 /etc/apt/keyrings

  # Add Kubernetes apt repository
  - curl -fsSL https://pkgs.k8s.io/core:/stable:/v1.32/deb/Release.key | sudo gpg --dearmor -o /etc/apt/keyrings/kubernetes-apt-keyring.gpg
  - echo 'deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.32/deb/ /' | sudo tee /etc/apt/sources.list.d/kubernetes.list

  # install containerd runtime
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor -o /etc/apt/keyrings/docker.gpg
  - echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" > /etc/apt/sources.list.d/docker.list
  - apt-get update
  - apt-get install -y containerd.io
  - mkdir -p /etc/containerd
  - systemctl start containerd
  - containerd config default > /etc/containerd/config.toml
  - sed -i 's/SystemdCgroup = false/SystemdCgroup = true/' /etc/containerd/config.toml
  - systemctl restart containerd
  - systemctl enable containerd

  # Install Kubernetes components
  - apt-get update
  - apt-get install -y kubelet kubeadm kubectl
  - apt-mark hold kubelet kubeadm kubectl

  # Wait for master node to be ready
  - until curl -k https://10.0.1.1:6443; do sleep 5; done

  # Get join command from master node and execute it
  - JOIN_COMMAND=$(ssh -o StrictHostKeyChecking=accept-new -i /home/cluster/.ssh/master_access cluster@10.0.1.1 'sudo kubeadm token create --print-join-command --kubeconfig=/etc/kubernetes/admin.conf')
  - $JOIN_COMMAND