apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-app
  namespace: web
spec:
  replicas: 3
  selector:
    matchLabels:
      app: web-app
  template:
    metadata:
      labels:
        app: web-app
    spec:
      containers:
        - name: web
          image: httpd:latest
          ports:
            - containerPort: 80
          volumeMounts:
            - name: apache-config
              mountPath: /usr/local/apache2/conf/extra/custom.conf
              subPath: custom.conf
      volumes:
        - name: apache-config
          configMap:
            name: apache-config
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ingress-nginx-controller
  namespace: ingress-nginx
data:
  allow-snippet-annotations: "true"
  compute-full-forwarded-for: "true"
  use-forwarded-headers: "true"
  use-proxy-protocol: "false"
  enable-access-log: "true"
  error-log-level: "debug"
  proxy-buffer-size: "8k"
  proxy-buffers-number: "4"
  proxy-connect-timeout: "15"
  proxy-read-timeout: "180"
  proxy-send-timeout: "180"
  proxy-real-ip-cidr: "173.245.48.0/20,103.21.244.0/22,103.22.200.0/22,103.31.4.0/22,141.101.64.0/18,108.162.192.0/18,190.93.240.0/20,188.114.96.0/20,197.234.240.0/22,198.41.128.0/17,162.158.0.0/15,104.16.0.0/13,104.24.0.0/14,172.64.0.0/13,131.0.72.0/22"