name: Nginx Kubernetes CI/CD

on:
  push:
    branches:
      - main
    paths:
      - 'kubernetes/nginx/**'
  workflow_dispatch:

jobs:
  kubernetes:
    uses: ./.github/workflows/kubernetes-base.yaml
    with:
      working_directory: kubernetes/nginx
    secrets:
      config: ${{ secrets.KUBE_CONFIG }}