name: Monitoring Kubernetes CI/CD

on:
  push:
    branches:
      - main
    paths:
      - 'kubernetes/monitoring/**'
  workflow_dispatch:

jobs:
  kubernetes:
    uses: ./.github/workflows/kubernetes-base.yaml
    with:
      working_directory: kubernetes/monitoring
    secrets:
      kube_config: ${{ secrets.KUBE_CONFIG }}