name: Node Exporter Kubernetes CI/CD

on:
  push:
    branches:
      - main
    paths:
      - 'kubernetes/monitoring/node-exporter/**'
  workflow_dispatch:

jobs:
  kubernetes:
    uses: ./.github/workflows/kubernetes-base.yaml
    with:
      working_directory: kubernetes/monitoring/node-exporter
    secrets:
      kube_config: ${{ secrets.KUBE_CONFIG }}