name: "Staging Terraform"

on:
  push:
    branches:
      - staging
    paths:
      - 'terraform/modules/**'
      - 'terraform/env/staging/**'
  pull_request:
    branches:
      - staging
    paths:
      - 'terraform/modules/**'
      - 'terraform/env/staging/**'
  workflow_dispatch:

jobs:
  terraform:
    uses: ./.github/workflows/terraform-base.yaml
    with:
      environment: staging
      working_directory: terraform/env/staging
      auto_approve: false  # Plan only in staging
    secrets:
      config: ${{ secrets.STAGING_CONFIG }}
      master_ssh_private_key: ${{ secrets.STAGING_MASTER_SSH_PRIVATE_KEY }}
      worker_ssh_private_key: ${{ secrets.STAGING_WORKER_SSH_PRIVATE_KEY }}
      master_ssh_public_key: ${{ secrets.STAGING_MASTER_SSH_PUBLIC_KEY }}
      worker_ssh_public_key: ${{ secrets.STAGING_WORKER_SSH_PUBLIC_KEY }}
      hcloud_token: ${{ secrets.STAGING_HCLOUD_TOKEN }}
      tf_api_token: ${{ secrets.TF_API_TOKEN }}