name: "Production Terraform"

on:
  push:
    branches:
      - main
    paths:
      - 'terraform/modules/**'
      - 'terraform/env/production/**'
  pull_request:
    branches:
      - main
    paths:
      - 'terraform/modules/**'
      - 'terraform/env/production/**'
  workflow_dispatch:

jobs:
  terraform:
    uses: ./.github/workflows/terraform-base.yaml
    with:
      environment: prod
      working_directory: terraform/env/production
      auto_approve: false
    secrets:
      config: ${{ secrets.PRODUCTION_CONFIG }}
      master_ssh_private_key: ${{ secrets.PROD_MASTER_SSH_PRIVATE_KEY }}
      worker_ssh_private_key: ${{ secrets.PROD_WORKER_SSH_PRIVATE_KEY }}
      master_ssh_public_key: ${{ secrets.PROD_MASTER_SSH_PUBLIC_KEY }}
      worker_ssh_public_key: ${{ secrets.PROD_WORKER_SSH_PUBLIC_KEY }}
      hcloud_token: ${{ secrets.PROD_HCLOUD_TOKEN }}
      tf_api_token: ${{ secrets.TF_API_TOKEN }}